# Generated by Django 5.1.3 on 2024-11-21 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribuidores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('distribuidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribuidores.distribuidores')),
            ],
        ),
    ]
