# Generated by Django 5.1.3 on 2024-11-21 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribuidores', '0003_remove_distribuidores_cantidad_comprada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad_comprada',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_por_unidad',
        ),
        migrations.AddField(
            model_name='distribuidores',
            name='cantidad_comprada',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='distribuidores',
            name='precio_por_unidad',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='distribuidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribuidores.distribuidores'),
        ),
    ]
