# Generated by Django 5.1.3 on 2024-12-02 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribuidores', '0004_remove_producto_cantidad_comprada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_factura', models.CharField(choices=[('1', 'Tipo A'), ('2', 'Tipo B')], max_length=20)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='distribuidores',
            name='precio_por_unidad',
        ),
        migrations.AddField(
            model_name='distribuidores',
            name='producto',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='distribuidores.producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_por_unidad',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='distribuidores',
            name='distribuidor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='distribuidores.distribuidor'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='distribuidor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='distribuidores.distribuidor'),
        ),
    ]
