# Generated by Django 5.1.3 on 2024-12-02 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distribuidores', '0005_distribuidor_remove_distribuidores_precio_por_unidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('stock', models.BooleanField()),
                ('producto', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='distribuidores.producto')),
            ],
        ),
    ]
